wifi.setmode(wifi.STATION)
wifi.sta.config(<SSID>, <PASSPHRASE>)
s=net.createServer(net.UDP)
s:on("receive", function(s,c) ws2812.writergb(6,c) end)
s:listen(6454)
c=net.createConnection(net.UDP)
c:connect(5683,"192.168.4.211")
gpio.mode(3,gpio.INPUT,gpio.PULLUP)
gpio.trig(3, "down", function()
    c:send("Button5")
end)
gpio.mode(4,gpio.INPUT,gpio.PULLUP)
gpio.trig(4, "down", function()
    c:send("Button3")
end)
gpio.mode(5,gpio.INPUT,gpio.PULLUP)
gpio.trig(5, "down", function()
    c:send("Button2")
end)
gpio.mode(1,gpio.INPUT,gpio.PULLUP)
gpio.trig(1, "down", function()
    c:send("Button4")
end)
gpio.mode(2,gpio.INPUT,gpio.PULLUP)
gpio.trig(2, "down", function()
    c:send("Button6")
end)
gpio.mode(7,gpio.INPUT,gpio.PULLUP)
gpio.trig(7, "down", function()
    c:send("Button1")
end)
